from django.conf.urls import patterns, url
import views

urlpatterns = patterns('',
                       url(r'^$', views.index, name='training_index'),
                       url(r'^add/$', views.training_form, name='add_training'),
                       url(r'^delete/(?P<pk>[0-9]+)/$', views.delete_training, name='delete_training'),
                       url(r'^list/$', views.list_trainings, name='list_trainings'),
                       url(r'^(?P<pk>[0-9]+)/$', views.training_form, name='update_training'),
                       url(r'^(?P<pk>[0-9]+)/print/$', views.print_training, name='print_training'),
                       url(r'^category/add/$', views.category_form, name='add_training_category'),
                       url(r'^categories/$', views.list_categories, name='list_training_categories'),
                       url(r'^category/(?P<pk>[0-9]+)/$', views.category_form, name='update_training_category'),
                       url(r'^category/(?P<pk>[0-9]+)/delete/$', views.delete_category, name='delete_category'),
                       url(r'^resource_person/add/$', views.resource_person_form, name='add_resource_person'),
                       url(r'^resource_person/(?P<pk>[0-9]+)/$', views.resource_person_form,
                           name='update_resource_person'),
                       url(r'^resource_persons/$', views.list_resource_persons, name='list_resource_persons'),
                       url(r'^resource_person/(?P<pk>[0-9]+)/delete/$', views.delete_resource_person,
                           name='delete_resource_person'),
                       url(r'^target_group/add/$', views.target_group_form, name='add_target_group'),
                       url(r'^target_group/(?P<pk>[0-9]+)/$', views.target_group_form, name='update_target_group'),
                       url(r'^target_groups/$', views.list_target_groups, name='list_target_groups'),
                       url(r'^target_group/(?P<pk>[0-9]+)/delete/$', views.delete_target_group,
                           name='delete_target_group'),
                       url(r'^participant/add/$', views.participant_form, name='add_participant'),
                       url(r'^participant/(?P<pk>[0-9]+)/$', views.participant_form, name='update_participant'),
                       url(r'^participants.json$', views.participants_as_json, name='participants_as_json'),
                       url(r'^participants/$', views.list_participants, name='list_participants'),
                       url(r'^participant/(?P<pk>[0-9]+)/delete/$', views.delete_participant,
                           name='delete_participant'),
                       url(r'^organization/add/$', views.organization_form, name='add_organization'),
                       url(r'^organization/(?P<pk>[0-9]+)/$', views.organization_form, name='update_organization'),
                       url(r'^organizations/$', views.list_organizations, name='list_organizations'),
                       url(r'^organization/(?P<pk>[0-9]+)/delete/$', views.delete_organization,
                           name='delete_organization'),
                       url(r'^files/$', views.list_files, name='list_files'),
                       url(r'^report/$', views.training_report, name='training_report'),
                       # url(r'^author/(?P<slug>[a-zA-Z0-9_.-]+)/$', views.view_author, name='view_author'),
                       # url(r'^search/(?P<keyword>.*)$', views.search, name='search'),
)
